name: Dispatch Submodule Update
on: push
env:
  submodule_name: dotfiles-test-sub1
  dotfiles_repo: rainbartown/dotfiles-test-main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "https://api.github.com/repos/${{ env.dotfiles_repo }}/dispatches" -d '{"event_type": "submodule_update", "client_payload": {"submodule_name": "${{ env.submodule_name }}"}}'
